import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

export interface PlayerData {
  id: string
  name: string
  father_name: string
  address: string
  email?: string
  player_code: string
  created_at: string
}

export interface PaymentData {
  id: string
  player_id: string
  amount: number
  date: string
  time: string
  installment_number: number
  player?: PlayerData
}

export interface InvestmentData {
  id: string
  expense_type: string
  amount: number
  quantity?: number
  date: string
  time: string
}

export interface ShuttleStock {
  id: string
  total_added: number
  remaining: number
  updated_at: string
}

class ModernPDFGenerator {
  private doc: jsPDF
  private pageWidth: number
  private pageHeight: number
  private margin: number = 20

  constructor() {
    this.doc = new jsPDF()
    this.pageWidth = this.doc.internal.pageSize.getWidth()
    this.pageHeight = this.doc.internal.pageSize.getHeight()
  }

  private addHeader(title: string) {
    // Header background with gradient effect
    this.doc.setFillColor(30, 58, 138) // Dark blue
    this.doc.rect(0, 0, this.pageWidth, 50, 'F')
    
    // Add accent line at bottom
    this.doc.setFillColor(59, 130, 246) // Light blue accent
    this.doc.rect(0, 48, this.pageWidth, 2, 'F')

    // Club name - centered at top
    this.doc.setTextColor(255, 255, 255)
    this.doc.setFontSize(22)
    this.doc.setFont('helvetica', 'bold')
    this.doc.text('Star Badminton Club', this.pageWidth / 2, 18, { align: 'center' })

    // Report title - centered below club name
    this.doc.setFontSize(16)
    this.doc.setFont('helvetica', 'bold')
    this.doc.text(title, this.pageWidth / 2, 32, { align: 'center' })

    // Website - bottom right
    this.doc.setFontSize(10)
    this.doc.setFont('helvetica', 'normal')
    this.doc.text('www.starbadminton.com', this.pageWidth - this.margin, 45, { align: 'right' })

    // Reset text color
    this.doc.setTextColor(0, 0, 0)
  }

  private addFooter() {
    const pageCount = this.doc.getNumberOfPages()
    
    for (let i = 1; i <= pageCount; i++) {
      this.doc.setPage(i)
      
      // Footer line
      this.doc.setDrawColor(200, 200, 200)
      this.doc.line(this.margin, this.pageHeight - 20, this.pageWidth - this.margin, this.pageHeight - 20)
      
      // Footer text
      this.doc.setFontSize(9)
      this.doc.setTextColor(128, 128, 128)
      this.doc.setFont('helvetica', 'normal')
      this.doc.text(
        `Generated by Star Badminton Club Assistant - Page ${i} of ${pageCount}`,
        this.pageWidth / 2,
        this.pageHeight - 10,
        { align: 'center' }
      )
    }
    
    this.doc.setTextColor(0, 0, 0)
  }

  private addWatermark() {
    const pageCount = this.doc.getNumberOfPages()
    
    for (let i = 1; i <= pageCount; i++) {
      this.doc.setPage(i)
      
      // Add watermark text
      this.doc.setFontSize(60)
      this.doc.setTextColor(240, 240, 240) // Very light gray
      this.doc.setFont('helvetica', 'bold')
      this.doc.text('Star Badminton', this.pageWidth / 2, this.pageHeight / 2, { 
        align: 'center',
        angle: 45
      })
      
      // Reset
      this.doc.setTextColor(0, 0, 0)
    }
  }

  private addSummaryBox(data: { label: string; value: string | number }[]) {
    const boxY = 45
    const boxHeight = 30
    const boxWidth = (this.pageWidth - 2 * this.margin - 10) / data.length

    // Background
    this.doc.setFillColor(243, 244, 246) // Light gray
    this.doc.rect(this.margin, boxY, this.pageWidth - 2 * this.margin, boxHeight, 'F')

    // Border
    this.doc.setDrawColor(200, 200, 200)
    this.doc.rect(this.margin, boxY, this.pageWidth - 2 * this.margin, boxHeight, 'S')

    // Data
    this.doc.setFontSize(10)
    this.doc.setTextColor(75, 85, 99)
    
    data.forEach((item, index) => {
      const x = this.margin + 10 + index * boxWidth
      
      // Label
      this.doc.setFont('helvetica', 'normal')
      this.doc.text(item.label, x + boxWidth / 2, boxY + 10, { align: 'center' })
      
      // Value
      this.doc.setFont('helvetica', 'bold')
      this.doc.setFontSize(14)
      this.doc.setTextColor(30, 58, 138)
      this.doc.text(String(item.value), x + boxWidth / 2, boxY + 22, { align: 'center' })
      
      // Reset
      this.doc.setFontSize(10)
      this.doc.setTextColor(75, 85, 99)
    })

    this.doc.setTextColor(0, 0, 0)
    return boxY + boxHeight + 10
  }

  generatePlayerRecordsPDF(
    players: PlayerData[],
    payments: PaymentData[],
    investments: InvestmentData[],
    shuttleStock: ShuttleStock,
    customTitle?: string
  ): void {
    this.doc = new jsPDF()
    
    // Add watermark first (behind everything)
    this.addWatermark()
    
    // Header - use custom title if provided
    const title = customTitle || 'Payment Records Report'
    this.addHeader(title)

    // Summary box
    const summaryY = this.addSummaryBox([
      { label: 'Total Payments', value: payments.length },
      { label: 'Total Amount', value: `Rs. ${payments.reduce((sum, p) => sum + p.amount, 0)}` },
      { label: 'Total Players', value: players.length },
      { label: 'Report Date', value: new Date().toLocaleDateString('en-US') }
    ])

    // Add spacing after summary box
    const sectionStartY = summaryY + 15
    
    // Payment Details Section
    this.doc.setFontSize(18)
    this.doc.setFont('helvetica', 'bold')
    this.doc.setTextColor(30, 58, 138)
    this.doc.text('Payment Details', this.margin, sectionStartY)
    this.doc.setTextColor(0, 0, 0)

    const paymentTableData = payments.map(payment => [
      payment.player?.player_code || 'N/A',
      payment.player?.name || 'N/A',
      `Rs. ${payment.amount}`,
      payment.installment_number.toString(),
      payment.date ? new Date(payment.date).toLocaleDateString('en-US') : 'N/A',
      payment.time
    ])

    autoTable(this.doc, {
      startY: sectionStartY + 8,
      head: [['Player Code', 'Player Name', 'Amount', 'Installment', 'Date', 'Time']],
      body: paymentTableData,
      theme: 'grid',
      headStyles: {
        fillColor: [30, 58, 138],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 10
      },
      bodyStyles: {
        fontSize: 9,
        cellPadding: 5
      },
      alternateRowStyles: {
        fillColor: [243, 244, 246]
      },
      margin: { left: this.margin, right: this.margin }
    })

    // Footer
    this.addFooter()

    // Save
    this.doc.save(`star-badminton-payments-${new Date().toISOString().split('T')[0]}.pdf`)
  }

  generateInvestmentsPDF(
    investments: InvestmentData[],
    shuttleStock: ShuttleStock
  ): void {
    this.doc = new jsPDF()
    
    // Add watermark first
    this.addWatermark()
    
    // Header
    this.addHeader('Expenses & Investments Report')

    // Summary box
    const totalInvestment = investments.reduce((sum, inv) => sum + inv.amount, 0)
    const summaryY = this.addSummaryBox([
      { label: 'Total Records', value: investments.length },
      { label: 'Total Investment', value: `Rs. ${totalInvestment}` },
      { label: 'Report Date', value: new Date().toLocaleDateString('en-US') },
      { label: 'Generated', value: new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' }) }
    ])

    // Add spacing after summary box
    const investmentSectionStartY = summaryY + 15
    
    // Investments Table Section
    this.doc.setFontSize(18)
    this.doc.setFont('helvetica', 'bold')
    this.doc.setTextColor(30, 58, 138)
    this.doc.text('Investment Details', this.margin, investmentSectionStartY)
    this.doc.setTextColor(0, 0, 0)

    const investmentTableData = investments.map(investment => [
      investment.expense_type,
      `Rs. ${investment.amount}`,
      investment.quantity?.toString() || 'N/A',
      investment.date ? new Date(investment.date).toLocaleDateString('en-US') : 'N/A',
      investment.time
    ])

    autoTable(this.doc, {
      startY: investmentSectionStartY + 8,
      head: [['Expense Type', 'Amount', 'Quantity', 'Date', 'Time']],
      body: investmentTableData,
      theme: 'grid',
      headStyles: {
        fillColor: [30, 58, 138],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 10
      },
      bodyStyles: {
        fontSize: 9,
        cellPadding: 5
      },
      alternateRowStyles: {
        fillColor: [243, 244, 246]
      },
      margin: { left: this.margin, right: this.margin }
    })

    // Shuttle Stock Section
    const lastY = (this.doc as any).lastAutoTable.finalY + 20
    
    this.doc.setFontSize(18)
    this.doc.setFont('helvetica', 'bold')
    this.doc.setTextColor(30, 58, 138)
    this.doc.text('Shuttle Stock Status', this.margin, lastY)
    this.doc.setTextColor(0, 0, 0)

    const shuttleTableData = [
      ['Total Added', shuttleStock.total_added.toString()],
      ['Remaining', shuttleStock.remaining.toString()],
      ['Used', (shuttleStock.total_added - shuttleStock.remaining).toString()],
      ['Last Updated', new Date(shuttleStock.updated_at).toLocaleString('en-US')]
    ]

    autoTable(this.doc, {
      startY: lastY + 5,
      head: [['Metric', 'Value']],
      body: shuttleTableData,
      theme: 'grid',
      headStyles: {
        fillColor: [30, 58, 138],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 10
      },
      bodyStyles: {
        fontSize: 9,
        cellPadding: 5
      },
      alternateRowStyles: {
        fillColor: [243, 244, 246]
      },
      margin: { left: this.margin, right: this.margin }
    })

    // Footer
    this.addFooter()

    // Save
    this.doc.save(`star-badminton-investments-${new Date().toISOString().split('T')[0]}.pdf`)
  }
}

export const pdfGenerator = new ModernPDFGenerator()